server {
    listen 80;
    server_name localhost;
    absolute_redirect off;
    port_in_redirect off;
    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass stura-erp-api:9000;
    }

    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}